[book]
title = "FunLang: F#로 만드는 프로그래밍 언어"
authors = ["Shohruh Makhkamov"]
language = "ko"
description = "fslex/fsyacc를 사용한 인터프리터 구축 튜토리얼"
src = "src"

[build]
build-dir = "../docs"
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/shohruh-abduakhatov-portfolio/LangTutorial"
edit-url-template = "https://github.com/shohruh-abduakhatov-portfolio/LangTutorial/edit/master/book/src/{path}"

[output.html.search]
enable = true
limit-results = 30
boost-title = 2
boost-hierarchy = 1
